services:
  asn-project:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: asn-project-image
    container_name: asn-project-container 
    volumes:
      # - ./workspace:/workspace
      # - /mnt/c/docker_share:/shared_data
      - C:\docker_share:/mounted_data:cached 
      # - C:\Users\Stephanie\repos\clones\YOLO-World:/yolo-world:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true