services:
  asn-project:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: asn-project-image
    container_name: asn-project-container 
    volumes:
      - C:\docker_share:/mounted_data:cached 
      - ..:/workspace:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true